apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-polling-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-polling-app
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: clusterBuilder
    value: full
  source:
    git:
      url: https://github.com/Eknathreddy09/python-polling-app
      ref:
        branch: main
